apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-prod
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: voting-app
  source:
    path: prod
    repoURL: https://github.com/mquang279/argo-labs.git
    targetRevision: release
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
