apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: vote-staging
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: vote-staging
      images:
        - alias: vote
          imageName: mquang279/vote
          commonUpdateSettings:
            updateStrategy: newest-build
            allowTags: regexp:^[0-9a-f]{7}$
            ignoreTags:
              - dev
            forceUpdate: true
          manifestTargets:
            kustomize:
              name: mquang279/vote

  writeBackConfig:
    method: git
    gitConfig:
      branch: main
      writeBackTarget: kustomization:../base